version: '3.4'

services:
  pg-database:
    build:
      context: ./myspaces-db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend_net

  db-web-ui:
    image: adminer
    restart: always
    depends_on:
      - pg-database
    ports:
      - 8080:8080
    networks:
      - backend_net

  chrome-browser:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - 4444:4444
    networks:
      - chrome

  python-backend:
    build:
      context: ./myspaces-server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - pg-database
      - chrome-browser
    ports:
      - 8000:8000
    networks:
      - backend_net
      - frontend_net
      - chrome
    volumes:
      - ./myspaces-server:/app

  react-frontend:
    build:
      context: ./myspaces-ui
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - python-backend
    ports:
      - 3000:3000
    networks:
      - frontend_net

networks:
  frontend_net:
  backend_net:
  chrome:
